name: Deploy to AWS VM

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:                                          
      - name: Checkout code #checkout repository     #STEP 1
        uses: actions/checkout@v2

      - name: Setup Node.js                          #STEP 2
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies                  #STEP 3
        run: npm install
          
      - name: Copy code to AWS VM 
        uses: appleboy/scp-action@master
        with:
          host: ${{  secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USERNAME }}
          key: ${{ secrets.AWS_SERVER_PRIVATE_KEY }}
          source: "."  
          target: "/var/www/html/Node-Test"    # Target directory on GCP VM
             
      - name: starting Listening on 3000
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP  }}
          username: ${{ secrets.AWS_SERVER_USERNAME }}
          key: ${{ secrets.AWS_SERVER_PRIVATE_KEY }} 
          script: |
            sudo npm install -g pm2
            cd /var/www/html/Node-Test
            sudo pm2 restart all 
